"""
Master Security Test Suite
Tüm testleri otomatik çalıştırır ve rapor oluşturur
"""

import subprocess
import json
from datetime import datetime
from colorama import init, Fore, Style

init()

def run_test_script(script_name, description):
    """Test scriptini çalıştır ve sonucu döndür"""
    print(f"\n{Fore.CYAN}{'=' * 70}{Style.RESET_ALL}")
    print(f"{Fore.CYAN}Running: {description}{Style.RESET_ALL}")
    print(f"{Fore.CYAN}{'=' * 70}{Style.RESET_ALL}\n")
    
    try:
        result = subprocess.run(
            ['python', script_name],
            capture_output=True,
            text=True,
            timeout=120,
            cwd=r'c:\Users\Esisya\.gemini\antigravity\scratch\LangChain_backend\security_tests'
        )
        
        return {
            'name': description,
            'script': script_name,
            'status': 'COMPLETED' if result.returncode == 0 else 'FAILED',
            'output': result.stdout + result.stderr
        }
    except subprocess.TimeoutExpired:
        return {
            'name': description,
            'script': script_name,
            'status': 'TIMEOUT',
            'output': 'Test exceeded 120 seconds'
        }
    except Exception as e:
        return {
            'name': description,
            'script': script_name,
            'status': 'ERROR',
            'output': str(e)
        }

def generate_final_report(results):
    """Nihai raporu oluştur"""
    
    report = f"""
╔══════════════════════════════════════════════════════════════════════╗
║                 LUMORA AI CHATBOT - SECURITY AUDIT REPORT           ║
║                      Comprehensive Penetration Test                  ║
╚══════════════════════════════════════════════════════════════════════╝

Report Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Target: Lumora AI Chatbot (Backend + Frontend)
Backend: http://localhost:8000
Frontend: http://localhost:3000

═══════════════════════════════════════════════════════════════════════
EXECUTIVE SUMMARY
═══════════════════════════════════════════════════════════════════════

Total Tests Run: {len(results)}
Completed: {sum(1 for r in results if r['status'] == 'COMPLETED')}
Failed: {sum(1 for r in results if r['status'] != 'COMPLETED')}

═══════════════════════════════════════════════════════════════════════
TEST RESULTS SUMMARY
═══════════════════════════════════════════════════════════════════════
"""
    
    for i, result in enumerate(results, 1):
        status_symbol = "✅" if result['status'] == 'COMPLETED' else "❌"
        report += f"\n[{i}] {status_symbol} {result['name']}\n"
        report += f"    Script: {result['script']}\n"
        report += f"    Status: {result['status']}\n"
        report += f"    {'─' * 66}\n"
    
    report += f"\n{'═' * 70}\n"
    report += f"DETAILED TEST OUTPUTS\n"
    report += f"{'═' * 70}\n\n"
    
    for result in results:
        report += f"\n{'█' * 70}\n"
        report += f"TEST: {result['name']}\n"
        report += f"{'█' * 70}\n\n"
        report += result['output']
        report += f"\n\n"
    
    report += f"\n{'═' * 70}\n"
    report += f"END OF REPORT\n"
    report += f"{'═' * 70}\n"
    report += f"\nGenerated by: Antigravity Security Assessment Tool\n"
    report += f"Report saved: FINAL_SECURITY_REPORT_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt\n"
    
    return report

if __name__ == "__main__":
    print(f"{Fore.RED}")
    print("╔══════════════════════════════════════════════════════════════════╗")
    print("║          LUMORA SECURITY AUDIT - AUTOMATED TEST SUITE           ║")
    print("╚══════════════════════════════════════════════════════════════════╝")
    print(f"{Style.RESET_ALL}\n")
    
    tests = [
        ('security_test.py', 'General Security Scan'),
        ('rate_limiting_test.py', 'Rate Limiting & Brute Force Test'),
        ('jwt_hijacking_test.py', 'JWT Token Security Test'),
        ('quick_xss_test.py', 'XSS Vulnerability Test'),
        ('server_health_check.py', 'Server Health Baseline'),
    ]
    
    results = []
    
    for script, description in tests:
        result = run_test_script(script, description)
        results.append(result)
        
        if result['status'] == 'COMPLETED':
            print(f"{Fore.GREEN}✅ {description} - PASSED{Style.RESET_ALL}")
        else:
            print(f"{Fore.RED}❌ {description} - {result['status']}{Style.RESET_ALL}")
    
    # Generate report
    print(f"\n{Fore.YELLOW}Generating final report...{Style.RESET_ALL}\n")
    
    final_report = generate_final_report(results)
    
    # Save to file
    filename = f"FINAL_SECURITY_REPORT_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(final_report)
    
    print(f"{Fore.GREEN}✅ Report saved: {filename}{Style.RESET_ALL}\n")
    
    # Summary
    print(f"{Fore.CYAN}{'=' * 70}{Style.RESET_ALL}")
    print(f"{Fore.CYAN}FINAL SUMMARY{Style.RESET_ALL}")
    print(f"{Fore.CYAN}{'=' * 70}{Style.RESET_ALL}\n")
    
    completed = sum(1 for r in results if r['status'] == 'COMPLETED')
    print(f"Total Tests: {len(results)}")
    print(f"Completed: {Fore.GREEN}{completed}{Style.RESET_ALL}")
    print(f"Failed: {Fore.RED}{len(results) - completed}{Style.RESET_ALL}")
    print(f"Success Rate: {(completed/len(results))*100:.1f}%\n")
    
    print(f"📄 Full report: {filename}\n")
